var GAME_LEVELS = [
  ["                                               v   x!!!!!!!x                    ",
   "                xxx                                xxxx!xxxx                    ",
   "                yyy                                   xvx                       ",
   "                               xxx                                              ",
   "                               yyy                                              ",
   "       xxx                                                                      ",
   "       yyy                                                                  xx  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                        xxxxxxx     x     xxxxxx             x  ",
   "                                              x     x     xx                 x  ",
   "                                              x     xx    xx                 x  ",
   "  xx                             xxx          x     x     xx         o       x  ",
   "  x          xxxx                yyy          x     x     xx                 x  ",
   "  x          xxxx         xxx          xxxxxxxx           xx                 x  ",
   "  x          xxxx         yyy                 x          xxx                 x  ",
   "  x  @       xxxx    xxx                      x xxxxxxx xxxx!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxx    yyy                      x x    x     x!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxx                             x x    x     x!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxx                             x x    x     x!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyxxxxxxx  "],
  ["!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x @ x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   x!!!!!x                                                            ",
   "!!!!!!!!!x   xyyyyyxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "!!!!!!!!!x                                    x                                 ",
   "!!!!!!!!!x                                    x                                 ",
   "!!!!!!!!!x       |       |       |            x                                 ",
   "!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x                                o",
   "!!!!!!!!!!!!!!!!!!xx     xx     xx   x=      =x                                x",
   "!!!!!!!!!!!!!!!!!!xx     xx     xx   xxxx  xxxx                                y",
   "!!!!!!!!!!!!!!!!!!xx     xx     xx      x  x                                    ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!!!!x  x!!                        xxx       ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!xxxx  xxxx                       yyy       ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!x                                          ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!x                       xxx                ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!x                       yyy                ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!x                                          ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!x                                          ",
   "!!!!!!!!!!!!!!!!!!xx!!!!!xx!!!!!xx!!!xxxxxxxxxxx!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                            v                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                 ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                 ",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!x                    xxxxxxxx xxxxxx       o      ",
   "     x!!!!!!!!!x!x!!!!!!!!!!!!x                   x            x xx             ",
   "      x!!!!xxxx v x!!!!!!!!!!!x              x    y            x  xx            ",
   "       xx!x        xxxxxx!!!!x          x    y                 x   xx           ",
   "         v               xx!x           y                      x                ",
   "                           v                          x        x                ",
   "                                                      x        x                ",
   "                                   xx=       |       =xxx      x                ",
   "                                   xxxxxxxxxxxxxxxxxxxx        x                ",
   "@                                                              x                ",
   "x            xx                                              xxx                ",
   "y            yy                                                x                ",
   "                                      |       |       |        x                ",
   "    xxx                            xxxxxxxxxxxxxxxxxxxxxxxx xxxx                ",
   "    yyy           x                yyyyyyyyyyyyyyyyyyyyyyyy yyyy                ",
   "                  y          x                                                  ",
   "                             y                                                  ",
   "                                                                                ",
   "                       x                                                        ",
   "                       y                                                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "            @                                                                      o           ",
   "           xx     xx      xxxx      xx    xx  xx  xx           xx    xx    xx     xx           ",
   "           xx     xx     xx  xx     xx    xx      xx           xx    xx    xxx    xx           ",
   "            xx   xx     xx    xx    xx    xx      xx    xxx    xx    xx    xxxx   xx           ",
   "             xx xx      xx    xx    xx    xx      xx    xxx    xx    xx    xx xx  xx           ",
   "              xxx       xx    xx    xx    xx      xx    xxx    xx    xx    xx  xx xx           ",
   "              xxx       xx!!!!xx    xx!!!!xx      xx!!!!xxx!!!!xx    xx    xx   xxxx           ",
   "              xxx        xx!!xx      xx!!xx        xx!!xx xx!!xx     xx    xx    xxx           ",
   "              xxx         xxxx        xxxx          xxxx   xxxx      xx    xx     xx           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
